MyDistanceLearningSystem/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDistanceLearningSystem.Models;
using PagedList.Mvc;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MyDistanceLearningSystem.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        public ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult ChatWithWebSockets()
        {
            return View();
        }
        
        public async Task<ActionResult> Index(string Name, int? TrainingProgramId, int? ItemCountPerPage, int page = 1)
        {
            int groupsCount;
            IEnumerable<Group> groupsPerPages;
            int pageSize = ItemCountPerPage != null ? (int)ItemCountPerPage : 5;
            if (User.IsInRole("admin"))
            {
                groupsCount = await db.Groups.CountAsync();
                groupsPerPages = await db.Groups.Include(g => g.TrainingProgram).ToListAsync();
            }else
            {
                int? GroupId = (await db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefaultAsync()).GroupId;
                groupsCount = await db.Groups.Where(g=>g.Id == GroupId).CountAsync();
                groupsPerPages = await db.Groups.Where(g => g.Id == GroupId).Include(g => g.TrainingProgram).ToListAsync();
            }
            if (!String.IsNullOrEmpty(Name))
            {
                groupsPerPages = groupsPerPages.Where(s => s.Name.IndexOf(Name) != -1);
                groupsCount = groupsPerPages.Count();
            }
            if (TrainingProgramId != null && TrainingProgramId != 0)
            {
                groupsPerPages = groupsPerPages.Where(s => s.TrainingProgramId == TrainingProgramId);
                groupsCount = groupsPerPages.Count();
            }
            groupsPerPages =
                groupsPerPages.OrderBy(g => g.Id).ThenBy(g => g.Name)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = groupsCount };
            var TrainingPrograms = await db.TrainingPrograms.Select(tp => new { Id = tp.Id, Name = tp.Name}).ToListAsync();
            TrainingPrograms.Add(new { Id = 0, Name = "Все программы"});
            IndexViewModel<Group> ivm = new IndexViewModel<Group>
            {
                PageInfo = pageInfo,
                Objects = groupsPerPages,
                Name = Name ?? "",
                TrainingPrograms = new SelectList(TrainingPrograms.OrderBy(tp=>tp.Id), "Id", "Name"),
                SelectedTrainingProgram = TrainingProgramId ?? 0
            };
            return View(ivm);


           /* int pageSize = 10;
            int pageNumber = (page ?? 1);
            var groups = db.Groups.Include(g => g.TrainingProgram);
            ViewBag.TrainingProgramId = new SelectList(db.TrainingPrograms, "Id", "Name", group.TrainingProgramId);
            return View(groups.ToList().ToPagedList(pageNumber, pageSize));*/
        }

        public async Task<ActionResult> StudentsList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            IEnumerable<ApplicationUser> students = await db.Users.Where(u => u.Roles.Any(r => r.RoleId == "0ccde516-98df-4ea6-9be2-efd467a98d1d") && u.GroupId == id).ToListAsync();
            ViewBag.Disciplines = await db.Disciplines.Where(d=>d.TrainingProgramId == group.TrainingProgramId).ToListAsync();
            return View(students);
        }
        
        public async Task<ActionResult> StudentsInfo(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.Teacher = await db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).Include(u=>u.Discipline).FirstOrDefaultAsync();
            return PartialView(user);
        }

        public async Task<ActionResult> GroupChat()
        {
           /* ViewBag.UserName =
            string TeacherId = db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefault().Id;*/

            ApplicationUser user = await UserManager.FindByEmailAsync(User.Identity.Name);
            return View(user);
        }

        // GET: Groups/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return PartialView(group);
        }
        
        public async Task<ActionResult> Create()
        {
            ViewBag.TrainingProgramId = new SelectList(db.TrainingPrograms.OrderBy(t=>t.Name), "Id", "Name");
            ViewBag.Disciplines = await (from d in db.Disciplines
                                   join u in db.Users on d.Id equals u.DisciplineId
                                   where d.TrainingProgramId == db.TrainingPrograms.OrderBy(t => t.Name).FirstOrDefault().Id
                                   select d).Distinct().ToListAsync();
            ViewBag.Students = await db.Users.Where(u => u.GroupId == null && u.Roles.Any(r => r.RoleId == "0ccde516-98df-4ea6-9be2-efd467a98d1d")).ToListAsync();
            string referrer = HttpContext.Request.UrlReferrer == null ? "/Groups" : HttpContext.Request.UrlReferrer.PathAndQuery;
            ViewBag.Referrer = referrer;
            return View();
        }
        
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Group group, String[] selectedStudents, List<string> teachers, string referrer = "")
        {
            if (ModelState.IsValid)
            {
                group.Students.Clear();
                if (selectedStudents != null)
                {
                    foreach (var u in db.Users.Where(us => selectedStudents.Contains(us.Id)))
                    {
                        group.Students.Add(u);
                    }
                }
                db.Groups.Add(group);
                await db.SaveChangesAsync();
                if (teachers != null)
                {
                    foreach (string t in teachers.Where(t => !String.IsNullOrEmpty(t)))
                    {
                        
                        ApplicationUser user = await UserManager.FindByIdAsync(t);
                        user.GroupId = group.Id;
                        IdentityResult result = await UserManager.UpdateAsync(user);
                        
                    }
                }
                //return RedirectToAction("Index", new { page = page });
                return Redirect(referrer);
            }
            ViewBag.TrainingProgramId = new SelectList(db.TrainingPrograms, "Id", "Name", group.TrainingProgramId);
            ViewBag.Students = await db.Users.Where(u => u.GroupId == null && u.Roles.Any(r => r.RoleId == "0ccde516-98df-4ea6-9be2-efd467a98d1d")).ToListAsync();
            ViewBag.Referrer = referrer;
            return View(group);
        }
        
        public async Task<ActionResult> Edit(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            string referrer = HttpContext.Request.UrlReferrer == null ? "/Groups" : HttpContext.Request.UrlReferrer.PathAndQuery;
            int trainingProgramId = (int)group.TrainingProgramId;
            ViewBag.Disciplines = await (from d in db.Disciplines
                                            join u in db.Users on d.Id equals u.DisciplineId
                                            where d.TrainingProgramId == trainingProgramId
                                            select d).Distinct().ToListAsync();

            ViewBag.TrainingProgramId = new SelectList(db.TrainingPrograms, "Id", "Name", group.TrainingProgramId);
            ViewBag.Students = await db.Users.Where(u => (u.GroupId == id || u.GroupId == null) && u.Roles.Any(r => r.RoleId == "0ccde516-98df-4ea6-9be2-efd467a98d1d")).ToListAsync();
            ViewBag.Referrer = referrer;
            return View(group);
        }
        
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Group group, String[] selectedStudents, List<string> teachers, string referrer = "")
        {

MyDistanceLearningSystem/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDistanceLearningSystem.Models;
using System.IO;
using MyDistanceLearningSystem.Functions;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MyDistanceLearningSystem.Controllers
{
    public class MessagesController : Controller
    {
        public ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Messages
       /* public ActionResult MessagesList()
        {
            ApplicationUser user = UserManager.FindByEmail(User.Identity.Name);
            IEnumerable<Message> messages = db.Messages.Where(m => m.ReceiverId == user.Id).Include(m => m.Sender).OrderByDescending(m => m.UploadDate).ToList();
            foreach (Message message in messages)
            {
                message.IsRead = true;
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
            }
            return View(messages);
        }*/
        public async Task<ActionResult> MessagesList(string Name, int? ItemCountPerPage, int page = 1)
        {
            ApplicationUser user = await UserManager.FindByEmailAsync(User.Identity.Name);
            IEnumerable<Message> messages = await db.Messages.Where(m => m.ReceiverId == user.Id).Include(m => m.Sender).OrderByDescending(m => m.UploadDate).ToListAsync();
            foreach (Message message in messages.Where(m=>m.IsRead == false))
            {
                message.IsRead = true;
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
            }

            int messagesCount;
            IEnumerable<Message> messagesPerPages;
            int pageSize = ItemCountPerPage != null ? (int)ItemCountPerPage : 5;
            
            messagesCount = messages.Count();
            messagesPerPages = messages;
            
            if (!String.IsNullOrEmpty(Name))
            {
                messagesPerPages = messagesPerPages.Where(s => s.Name.IndexOf(Name) != -1);
                messagesCount = messagesPerPages.Count();
            }

            messagesPerPages =
                messagesPerPages.OrderByDescending(m => m.UploadDate).ThenBy(g => g.Name)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = messagesCount };
            IndexViewModel<Message> ivm = new IndexViewModel<Message>
            {
                PageInfo = pageInfo,
                Objects = messagesPerPages,
                Name = Name ?? ""
            };
            return View(ivm);
        }
        [HttpGet]
        public async Task<ActionResult> Create(string Id)
        {
            if(Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            /*ApplicationUser user = UserManager.FindById(receiverId);
            if (user == null)  return HttpNotFound();*/
            ViewBag.ReceiverId = Id;
            var Sender = await UserManager.FindByEmailAsync(User.Identity.Name);
            ViewBag.SenderId = Sender.Id;
            ViewBag.SenderName = Sender.Name;
            return PartialView();
        }
        public ActionResult UnreadMesagesCountSelect()
        {
            ApplicationUser user = db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefault();

            ViewBag.UnreadMesagesCount = user != null ? db.Messages.Where(m => m.ReceiverId == user.Id && m.IsRead == false).Count() : 0;

            return PartialView();
        }
        /*public ActionResult Create1()
        {
            
            return View();
        }*/
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await db.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return PartialView(message);
        }
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await db.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            
            db.Messages.Remove(message);
            await db.SaveChangesAsync();
            return RedirectToAction("MessagesList");
            
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyDistanceLearningSystem/Views/Shared/_Layout.cshtml
@using MyDistanceLearningSystem.Models
@{
    /*ApplicationDbContext db = new ApplicationDbContext();
    ApplicationUser user = db.Users.Where(u => String.Equals(u.Email, Context.User.Identity.Name)).FirstOrDefault();
    
    ViewBag.UnreadMesagesCount = user != null ? db.Messages.Where(m => m.ReceiverId == user.Id && m.IsRead == false).Count() : 0;
    var a = 0;*/
}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <input id="SenderUserName" type="hidden" value="@User.Identity.Name" />
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("СДО", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Пользователи", "UsersList", "Account")</li>
                        <li>@Html.ActionLink("Программы обучения", "Index", "TrainingPrograms")</li>
                        <li>@Html.ActionLink("Дисциплины", "Index", "Disciplines")</li>
                        <li>@Html.ActionLink("Группы", "Index", "Groups")</li>
                        <li>@Html.ActionLink("Библиотека", "Index", "ApplicationFiles")</li>
                    }
                    @if (User.IsInRole("teacher"))
                    {
                        <li>@Html.ActionLink("Дисциплины", "Index", "Disciplines")</li>
                        <li>@Html.ActionLink("Группы", "Index", "Groups")</li>
                        <li>@Html.ActionLink("Библиотека", "Index", "ApplicationFiles")</li>
                        <li>@Html.ActionLink("Групповой чат", "GroupChat", "Groups")</li>
                    }
                    @if (User.IsInRole("student"))
                    {
                        <li>@Html.ActionLink("Обучение", "InterfaceForStudents", "Disciplines")</li>
                        <li>@Html.ActionLink("Группа", "Index", "Groups")</li>
                        <li>@Html.ActionLink("Библиотека", "Index", "ApplicationFiles")</li>
                        <li>@Html.ActionLink("Групповой чат", "GroupChat", "Groups")</li>
                    }
                    <li id="messages"><a href="@Url.Action("MessagesList", "Messages")">Сообщения @{Html.RenderAction("UnreadMesagesCountSelect", "Messages");} </a></li>
                    <li>@Html.ActionLink("О системе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src='@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")'></script>
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Ссылка на автоматически сгенерированный скрипт хаба SignalR -->
    <script src="~/signalr/hubs"></script>
    <script src='@Url.Content("~/Scripts/messager_function.js")'></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>