MyDistanceLearningSystem/Controllers/TrainingProgramsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDistanceLearningSystem.Models;

namespace MyDistanceLearningSystem.Controllers
{
    [Authorize(Roles = "admin")]
    public class TrainingProgramsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public async Task<ActionResult> Index(string Name, int? ItemCountPerPage, int page = 1)
        {
            int pageSize = ItemCountPerPage != null ? (int)ItemCountPerPage : 5;
            int programsCount = await db.TrainingPrograms.CountAsync();
            IEnumerable<TrainingProgram> programsPerPages = await db.TrainingPrograms.ToListAsync();
            if (!String.IsNullOrEmpty(Name))
            {
                programsPerPages = programsPerPages.Where(s => s.Name.IndexOf(Name) != -1);
                programsCount = programsPerPages.Count();
            }
            programsPerPages =
                programsPerPages.OrderBy(g => g.Id).ThenBy(g => g.Name)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = programsCount };
            IndexViewModel<TrainingProgram> ivm = new IndexViewModel<TrainingProgram>
            {
                PageInfo = pageInfo,
                Objects = programsPerPages,
                Name = Name ?? ""
            };
            return View(ivm);
        }
        
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainingProgram trainingProgram = await db.TrainingPrograms.FindAsync(id);
            if (trainingProgram == null)
            {
                return HttpNotFound();
            }
            return PartialView(trainingProgram);
        }
        
        
        public async Task<ActionResult> Create()
        {
            ViewBag.Disciplines = await db.Disciplines.Where(d => d.TrainingProgramId == null).ToListAsync();
            ViewBag.Groups = await db.Groups.Where(g => g.TrainingProgramId == null).ToListAsync();
            string referrer = HttpContext.Request.UrlReferrer == null ? "/TrainingPrograms" : HttpContext.Request.UrlReferrer.PathAndQuery;
            ViewBag.Referrer = referrer;
            return View();
        }
        
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TrainingProgram trainingProgram, int[] selectedDisciplines, int[] selectedGroups, string referrer = "")
        {
            if (ModelState.IsValid)
            {
                TrainingProgram newtrainingProgram = new TrainingProgram();
                newtrainingProgram.Name = trainingProgram.Name;
                if (selectedDisciplines != null)
                {
                    foreach (var d in db.Disciplines.Where(di => selectedDisciplines.Contains(di.Id)))
                    {
                        newtrainingProgram.Disciplines.Add(d);
                    }
                }
                if (selectedGroups != null)
                {
                    foreach (var g in db.Groups.Where(gr => selectedGroups.Contains(gr.Id)))
                    {
                        newtrainingProgram.Groups.Add(g);
                    }
                }
                db.TrainingPrograms.Add(newtrainingProgram);
                await db.SaveChangesAsync();
                //return RedirectToAction("Index");
                return Redirect(referrer);
            }
            ViewBag.Referrer = referrer;
            return View(trainingProgram);
            
        }
        [HttpGet]
        public ActionResult CreateDiscipline(int? trainingProgramId, bool isTrainingProgramCreate = false)
        {
            if (trainingProgramId == null && isTrainingProgramCreate == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.TrainingProgramId = trainingProgramId;
            return PartialView();
        }
        
        [HttpPost]
        public async Task<JsonResult> CreateDiscipline(Discipline d)
        {
            db.Disciplines.Add(d);
            await db.SaveChangesAsync();
            return Json(d);
        }
        [HttpGet]
        public ActionResult CreateGroup(int? trainingProgramId, bool isTrainingProgramCreate = false)
        {
            if (trainingProgramId == null && isTrainingProgramCreate == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.TrainingProgramId = trainingProgramId;
            return PartialView();
        }
        [HttpPost]
        public async Task<JsonResult> CreateGroup(Group g)
        {

            db.Groups.Add(g);
            await db.SaveChangesAsync();
            return Json(g);
        }
        
       
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainingProgram trainingProgram = await db.TrainingPrograms.FindAsync(id);
            if (trainingProgram == null)
            {
                return HttpNotFound();
            }
            ViewBag.Disciplines = await db.Disciplines.Where(d=>d.TrainingProgramId == id || d.TrainingProgramId == null).ToListAsync();
            ViewBag.Groups = await db.Groups.Where(g => g.TrainingProgramId == id || g.TrainingProgramId == null).ToListAsync();
            string referrer = HttpContext.Request.UrlReferrer == null ? "/TrainingPrograms" : HttpContext.Request.UrlReferrer.PathAndQuery;
            ViewBag.Referrer = referrer;
            return View(trainingProgram);
        }
       
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TrainingProgram trainingProgram, int[] selectedDisciplines, int[] selectedGroups, string referrer = "")
        {
            if (ModelState.IsValid)
            {
                TrainingProgram newtrainingProgram = await db.TrainingPrograms.FindAsync(trainingProgram.Id);
                newtrainingProgram.Name = trainingProgram.Name;
                newtrainingProgram.Disciplines.Clear();
                if (selectedDisciplines != null)
                {
                    foreach (var d in db.Disciplines.Where(di => selectedDisciplines.Contains(di.Id)))
                    {
                        newtrainingProgram.Disciplines.Add(d);
                    }
                }
                newtrainingProgram.Groups.Clear();
                if (selectedGroups != null)
                {
                    foreach (var g in db.Groups.Where(gr => selectedGroups.Contains(gr.Id)))
                    {
                        newtrainingProgram.Groups.Add(g);
                    }
                }
                db.Entry(newtrainingProgram).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Redirect(referrer);
            }
            ViewBag.Referrer = referrer;
            return View(trainingProgram);
        }
        
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainingProgram trainingProgram = await db.TrainingPrograms.FindAsync(id);
            if (trainingProgram == null)
            {
                return HttpNotFound();
            }
            ViewBag.Disciplines = await db.Disciplines.Where(d => d.TrainingProgramId == id).ToListAsync();
            ViewBag.Groups = await db.Groups.Where(g => g.TrainingProgramId == id).ToListAsync();
            string referrer = HttpContext.Request.UrlReferrer == null ? "/TrainingPrograms" : HttpContext.Request.UrlReferrer.PathAndQuery;
            ViewBag.Referrer = referrer;
            return View(trainingProgram);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id, string referrer = "")
        {
            //TrainingProgram trainingProgram = await db.TrainingPrograms.FindAsync(id);
            //https://professorweb.ru/my/entity-framework/6/level2/2_3.php
            TrainingProgram trainingProgram = await db.TrainingPrograms.Include(t => t.Disciplines).Include(t => t.Groups).FirstOrDefaultAsync(t => t.Id == id);
            db.TrainingPrograms.Remove(trainingProgram);
            await db.SaveChangesAsync();
            return Redirect(referrer);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public async Task<ActionResult> DisciplineList()
        {
            return PartialView(await db.Disciplines.ToListAsync());
        }
    }
}

MyDistanceLearningSystem/Views/TrainingPrograms/Create.cshtml
@model MyDistanceLearningSystem.Models.TrainingProgram
@using MyDistanceLearningSystem.Models
@{
    ViewBag.Title = "Create program";
}

<h2>Создание программы</h2>
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>TrainingProgram</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Disciplines, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div style="height: 200px; width:280px; overflow-y: scroll;" id="disciplines">
                    @{
                        List<Discipline> disciplines = ViewBag.Disciplines;
                        foreach (Discipline d in disciplines)
                        {
                            <input type="checkbox" name="selectedDisciplines" value="@d.Id" />@d.Name <br />
                        }
                    }
                </div>
            </div>
            <div class="col-md-10 col-md-push-2">@Html.ActionLink("Добавить новую дисциплину", "CreateDiscipline", new { isTrainingProgramCreate = true }, new { id = "create_discipline", @class = "btn btn-success btn-xs", title = "Добавить новую дисциплину" })</div>
            
            
            
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Groups, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div style="height: 200px; width:280px; overflow-y: scroll;" id="groups">
                    @{
                        List<Group> groups = ViewBag.Groups;
                        foreach (Group g in groups)
                        {
                            <input type="checkbox" name="selectedGroups" value="@g.Id" />@g.Name <br />
                        }
                    }
                </div>
            </div>
            <div class="col-md-10 col-md-push-2">@Html.ActionLink("Добавить новую группу", "CreateGroup", new { isTrainingProgramCreate = true }, new { id = "create_group", @class = "btn btn-success btn-xs", title = "Добавить новую группу" })</div>
        </div>
        
       
        @Html.Hidden("referrer", ViewBag.Referrer as String)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    <a href="@ViewBag.Referrer">Back to List</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

                $(function () {
                    $.ajaxSetup({ cache: false });
                    $("#create_discipline, #create_group").click(function (e) {

                        e.preventDefault();
                        $.get(this.href, function (data) {
                            $('#dialogContent').html(data);
                            $('#modDialog').modal('show');
                        });
                    });
                })
    </script>
}

MyDistanceLearningSystem/Views/TrainingPrograms/CreateDiscipline.cshtml
@model MyDistanceLearningSystem.Models.Discipline
<script type="text/javascript">
        function OnSuccess(data) {
            $('#disciplines').append('<input type="checkbox" name="selectedDisciplines" value="' + data.Id + '" checked="checked">' + data.Name + '<br>');
            $('.close').click();
        }
           /* $('#123').click(function () {
                alert('1');
                $.ajax({
                    type: "GET",
                    url: "/TrainingPrograms/CreateDiscipline1",
                    data: "name=" + $('#Discipline').val(),
                    success: function (data) {
                        $('#disciplines').append('<input type="checkbox" name="selectedDisciplines" value="' + data + '" checked="checked">' + $('#Discipline').val() + '<br>');
                    }
                });
            });*/

</script>
<!--<label class="control-label col-md-2" for="Discipline">Ваше имя:</label>
<input class="form-control text-box single-line valid" id="Discipline" name ="Discipline" type="text" size="40">
<div id="123">Добавить дисциплину</div>-->
<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Создание дисциплины</h4>
    </div>
    <div class="modal-body">
        @using (Ajax.BeginForm("CreateDiscipline", new AjaxOptions { OnSuccess = "OnSuccess" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.Hidden("TrainingProgramId", ViewBag.TrainingProgramId as int?)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
}

MyDistanceLearningSystem/Views/TrainingPrograms/CreateGroup.cshtml
@model MyDistanceLearningSystem.Models.Group
<script type="text/javascript">
        function OnSuccess(data) {
            $('#groups').append('<input type="checkbox" name="selectedGroups" value="' + data.Id + '" checked="checked">' + data.Name + '<br>');
            $('.close').click();
        }
</script>
<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Создание дисциплины</h4>
    </div>
    <div class="modal-body">
        @using (Ajax.BeginForm("CreateGroup", new AjaxOptions { OnSuccess = "OnSuccess" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.Hidden("TrainingProgramId", ViewBag.TrainingProgramId as int?)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MyDistanceLearningSystem/Views/TrainingPrograms/Delete.cshtml
@model MyDistanceLearningSystem.Models.TrainingProgram
@using MyDistanceLearningSystem.Models
@{
    ViewBag.Title = "Delete program";
}

<h2>Удаление программы</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrainingProgram</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        @if (ViewBag.Disciplines.Count > 0 || ViewBag.Groups.Count > 0)
        {
            <dt>
                Связи
            </dt>

            <dd>
                <div>
                    @(ViewBag.Disciplines.Count > 0 ? "Дисциплины:" : "")
                    <ul>
                        @{
                            List<Discipline> disciplines = ViewBag.Disciplines;
                            foreach (Discipline d in disciplines)
                            {
                                <li>@d.Name</li>
                            }
                        }
                    </ul>
                </div>
                <div>
                    @(ViewBag.Groups.Count > 0 ? "Группы:" : "")
                    <ul>
                        @{
                            List<Group> groups = ViewBag.Groups;
                            foreach (Group g in groups)
                            {
                                <li>@g.Name</li>
                            }
                        }
                    </ul>
                </div>
            </dd>
        }

    </dl>
    
        
   

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.Hidden("referrer", ViewBag.Referrer as String)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a href="@ViewBag.Referrer">Back to List</a>
        </div>
    }
</div>

MyDistanceLearningSystem/Views/TrainingPrograms/Details.cshtml
@model MyDistanceLearningSystem.Models.TrainingProgram

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Информация о программе</h4>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

        </dl>

    </div>
</div>

MyDistanceLearningSystem/Views/TrainingPrograms/DisciplineList.cshtml
@model IEnumerable<MyDistanceLearningSystem.Models.Discipline>


<table class="table">
@foreach (var item in Model) {
    <tr id="@item.Id">
        <td>
            @Html.CheckBox(item.Id.ToString(), false)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <!--<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>-->
    </tr>
}

</table>

MyDistanceLearningSystem/Views/TrainingPrograms/Edit.cshtml
@model MyDistanceLearningSystem.Models.TrainingProgram
@using MyDistanceLearningSystem.Models

@{
    ViewBag.Title = "Edit program";
}

<h2>Редактирование программы</h2>
<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TrainingProgram</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Disciplines, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div style="height: 200px; width:280px; overflow-y: scroll;" id="disciplines">
                    @{
                        List<Discipline> disciplines = ViewBag.Disciplines;
                        foreach (Discipline d in disciplines)
                        {
                            <input type="checkbox" name="selectedDisciplines" value="@d.Id"
                                   @(Model.Disciplines.Contains(d) ? "checked=\"checked\"" : "") />@d.Name <br />
                        }
                    }
                </div>
            </div>
            <div class="col-md-10 col-md-push-2">@Html.ActionLink("Добавить новую дисциплину", "CreateDiscipline", new { trainingProgramId = Model.Id }, new { id = "create_discipline", @class = "btn btn-success btn-xs", title = "Добавить новую дисциплину" })</div>
            
            <!--<div>@Ajax.ActionLink("Добавить новую дисциплину", "CreateDiscipline", "TrainingPrograms", new { trainingProgramId = @Model.Id }, new AjaxOptions { UpdateTargetId = "disciplines_selection" })</div>
            <div id="disciplines_selection" class="col-xs-12 col-md-4"></div>-->
            
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Groups, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div style="height: 200px; width:280px; overflow-y: scroll;" id="groups">
                    @{
                        List<Group> groups = ViewBag.Groups;
                        foreach (Group g in groups)
                        {
                            <input type="checkbox" name="selectedGroups" value="@g.Id"
                                   @(Model.Groups.Contains(g) ? "checked=\"checked\"" : "") />@g.Name <br />
                        }
                    }
                </div>
            </div>
            <div class="col-md-10 col-md-push-2">@Html.ActionLink("Добавить новую группу", "CreateGroup", new { trainingProgramId = Model.Id }, new { id = "create_group", @class = "btn btn-success btn-xs", title = "Добавить новую группу" })</div>
        </div>
        
       
        @Html.Hidden("referrer", ViewBag.Referrer as String)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@ViewBag.Referrer">Back to List</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

            $(function () {
                $.ajaxSetup({ cache: false });
                $("#create_discipline, #create_group").click(function (e) {

                    e.preventDefault();
                    $.get(this.href, function (data) {
                        $('#dialogContent').html(data);
                        $('#modDialog').modal('show');
                    });
                });
            })
    </script>
}

MyDistanceLearningSystem/Views/TrainingPrograms/Index.cshtml
@model MyDistanceLearningSystem.Models.IndexViewModel<MyDistanceLearningSystem.Models.TrainingProgram>
@using MyDistanceLearningSystem.Helpers
@{
    ViewBag.Title = "Programs";
}

<h2>Программы</h2>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div class="spinner text-center">
    <i class="load"></i>
</div>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<form method="get">
    <div class="form-inline">
        <input id="page" name="page" type="hidden" value="1" />
        <label class="control-label">Название программы: </label>
        @Html.TextBox("Name", Model.Name as String, htmlAttributes: new { @class = "form-control", placeholder = "Название программы" })
        <label class="control-label">Количество элементов на странице: </label>
        @Html.DropDownList("ItemCountPerPage", new SelectList(new int[] { 5, 10, 50, 100 }), htmlAttributes: new { @class = "form-control item-count-per-page-select" })
        <input type="submit" value="Фильтр" class="btn btn-default" />
    </div>
</form>
<br />
<table class="table">
    <tr>
        <th>
            Название программы
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Objects)
    {
        <tr>
            <td>
                <span class="program" id="@item.Id">
                    @Html.DisplayFor(modelItem => item.Name)
                </span>
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />
<div class="btn-group pages">
    @Html.PageLinqs(Model.PageInfo, Model.Name, Model.SelectedTrainingProgram, (n, tp, icpp, p) => Url.Action("Index", new { Name = n, TrainingProgramId = tp, ItemCountPerPage = icpp, page = p }))
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/js_functions")

    <script type="text/javascript">
        $('.pages a').bind('click', function () {
            $('#page').val($('.pages a.selected').html());
        });
        modal_window("program", "@Url.RouteUrl(new { controller = "TrainingPrograms", action = "Details" })");
        
    </script>
}