MyDistanceLearningSystem/Controllers/ApplicationFilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDistanceLearningSystem.Models;
using System.IO;
using MyDistanceLearningSystem.Functions;

namespace MyDistanceLearningSystem.Controllers
{
    [Authorize]
    public class ApplicationFilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationFiles
        /*public async Task<ActionResult> Index()
        {
            var applicationFiles = db.ApplicationFiles.Include(a => a.Discipline).Include(a => a.Teacher);
            return View(await applicationFiles.ToListAsync());
        }*/
        public async Task<ActionResult> Index(string Name, int? DisciplineId, string TeacherId, int? ItemCountPerPage, int page = 1)
        {
            int pageSize = ItemCountPerPage != null ? (int)ItemCountPerPage : 5;
            int filesCount = await db.ApplicationFiles.Where(f=>!f.IsHomeWork).CountAsync();
            IEnumerable<ApplicationFile> filesPerPages = await db.ApplicationFiles.Where(f => !f.IsHomeWork).Include(f => f.Discipline).Include(f => f.Teacher).ToListAsync();
            if (!String.IsNullOrEmpty(Name))
            {
                filesPerPages = filesPerPages.Where(d => d.DisplayName.IndexOf(Name) != -1);
                filesCount = filesPerPages.Count();
            }
            if (DisciplineId != null && DisciplineId != 0)
            {
                filesPerPages = filesPerPages.Where(f => f.DisciplineId == DisciplineId);
                filesCount = filesPerPages.Count();
            }
            filesPerPages =
                filesPerPages.OrderBy(f => f.Id).ThenBy(f => f.DisplayName)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = filesCount };

            var Disciplines = await db.Disciplines.Select(d => new { Id = d.Id, Name = d.Name }).ToListAsync();
            Disciplines.Add(new { Id = 0, Name = "Все дисциплины" });
            ViewBag.Disciplines = new SelectList(Disciplines.OrderBy(d => d.Id), "Id", "Name");

            var Teachers = await db.Users.Select(u => new { Id = u.Id, Name = u.Name }).ToListAsync();
            Teachers.Add(new { Id = Guid.Empty.ToString(), Name = "Все преподаватели" });
            ViewBag.Teachers = new SelectList(Teachers.OrderBy(u => u.Id), "Id", "Name");

            ViewBag.Discipline = (await db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefaultAsync()).DisciplineId;
            ViewBag.Teacher = (await db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefaultAsync()).Id;
            IndexViewModel<ApplicationFile> ivm = new IndexViewModel<ApplicationFile>
            {
                PageInfo = pageInfo,
                Objects = filesPerPages,
                Name = Name ?? "",
                SelectedDiscipline = DisciplineId ?? 0,
                SelectedTeacher = TeacherId ?? Guid.Empty.ToString()
            };
            return View(ivm);

        }
        
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationFile applicationFile = await db.ApplicationFiles.Include(f => f.Discipline).Include(f => f.Teacher).Where(f=>f.Id == id).FirstOrDefaultAsync();
            if (applicationFile == null)
            {
                return HttpNotFound();
            }
            //.FindAsync(id)
            return PartialView(applicationFile);
        }

        public async Task<ActionResult> GetFile(int? id, bool isHomeWork = false)
        {
            if(id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ApplicationFile file = await db.ApplicationFiles.FindAsync(id);
            string dir = isHomeWork ? "HomeWorks/" : "Disciplines/";
            string file_path = Server.MapPath("~/Files/" + dir + file.DisciplineId + "/" + file.FileName);
            string file_type = "application/octet-stream";
            string file_name = file.DisplayName + (file.FileName.Split('.').Any() ? "." + file.FileName.Split('.').LastOrDefault() : String.Empty);
            return File(file_path, file_type, file_name);
        }
        
        public async Task<ActionResult> Create()
        {
            string TeacherId = (await db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefaultAsync()).Id;
            if (User.IsInRole("admin"))
            {
                ViewBag.DisciplineId = new SelectList(db.Disciplines, "Id", "Name");
            }
            else
            {
                ViewBag.DisciplineId = new SelectList(db.Disciplines.Where(d => db.Users.Where(u => String.Equals(u.Id, TeacherId)).FirstOrDefault().DisciplineId == d.Id), "Id", "Name");
            }
            ViewBag.TeacherId = TeacherId;
            string referrer = HttpContext.Request.UrlReferrer == null ? "/ApplicationFiles" : HttpContext.Request.UrlReferrer.PathAndQuery;
            ViewBag.Referrer = referrer;
            return View();
        }
        
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,DisplayName,FileName,TeacherId,UploadDate,DisciplineId")] ApplicationFile applicationFile, HttpPostedFileBase file, string referrer = "")
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    FileInfo fileInf = new FileInfo(Server.MapPath("~/Files/Disciplines/" + applicationFile.DisciplineId + "/" + applicationFile.FileName));
                    /*if (fileInf.Exists)
                    {
                        fileInf.Delete();
                    }*/
                    file.SaveAs(Server.MapPath("~/Files/Disciplines/" + applicationFile.DisciplineId + "/" + Path.GetFileName(file.FileName)));

                    //?
                    applicationFile.FileName = HashCreator.GetHashString(DateTime.Now.ToString() + Path.GetFileName(file.FileName)) + Path.GetExtension(file.FileName);// (DateTime.Now.ToString() + Path.GetFileName(file.FileName)).GetHashCode().ToString();

                    db.ApplicationFiles.Add(applicationFile);
                    await db.SaveChangesAsync();
                    //return RedirectToAction("Index");
                    return Redirect(referrer);

                }
                
            }

            //ViewBag.DisciplineId = new SelectList(db.Disciplines, "Id", "Name", applicationFile.DisciplineId);
            string TeacherId = (await db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefaultAsync()).Id;
            if (User.IsInRole("admin"))
            {
                ViewBag.DisciplineId = new SelectList(db.Disciplines, "Id", "Name", applicationFile.DisciplineId);
            }
            else
            {
                ViewBag.DisciplineId = new SelectList(db.Disciplines.Where(d => db.Users.Where(u => String.Equals(u.Id, TeacherId)).FirstOrDefault().DisciplineId == d.Id), "Id", "Name");
            }
            ViewBag.TeacherId = TeacherId; //new SelectList(db.Users, "Id", "Name", applicationFile.TeacherId);
            ViewBag.Referrer = referrer;
            return View(applicationFile);
        }
        
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationFile applicationFile = await db.ApplicationFiles.FindAsync(id);
            if (applicationFile == null)
            {
                return HttpNotFound();
            }
            //ViewBag.DisciplineId = new SelectList(db.Disciplines, "Id", "Name", applicationFile.DisciplineId);
            // string TeacherId = db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefault().Id;
            ViewBag.Teacher = (await db.Users.Where(u => String.Equals(applicationFile.TeacherId, u.Id)).FirstAsync()).Name; ;
            if (User.IsInRole("admin"))
            {
                ViewBag.DisciplineId = new SelectList(db.Disciplines, "Id", "Name", applicationFile.DisciplineId);
            }
            else
            {
                
                ViewBag.DisciplineId = new SelectList(db.Disciplines.Where(d => db.Users.Where(u => String.Equals(u.Id, applicationFile.TeacherId)).FirstOrDefault().DisciplineId == d.Id), "Id", "Name");
            }
            string referrer = HttpContext.Request.UrlReferrer == null ? "/ApplicationFiles" : HttpContext.Request.UrlReferrer.PathAndQuery;
            ViewBag.Referrer = referrer;
            return View(applicationFile);
        }
        
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,DisplayName,FileName,TeacherId,UploadDate,DisciplineId")]ApplicationFile applicationFile, HttpPostedFileBase file, string referrer = "")
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    /*if (fileInf.Exists)
                    {
                        fileInf.Delete();

MyDistanceLearningSystem/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyDistanceLearningSystem.Models;
using System.IO;
using MyDistanceLearningSystem.Functions;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MyDistanceLearningSystem.Controllers
{
    public class MessagesController : Controller
    {
        public ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Messages
       /* public ActionResult MessagesList()
        {
            ApplicationUser user = UserManager.FindByEmail(User.Identity.Name);
            IEnumerable<Message> messages = db.Messages.Where(m => m.ReceiverId == user.Id).Include(m => m.Sender).OrderByDescending(m => m.UploadDate).ToList();
            foreach (Message message in messages)
            {
                message.IsRead = true;
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
            }
            return View(messages);
        }*/
        public async Task<ActionResult> MessagesList(string Name, int? ItemCountPerPage, int page = 1)
        {
            ApplicationUser user = await UserManager.FindByEmailAsync(User.Identity.Name);
            IEnumerable<Message> messages = await db.Messages.Where(m => m.ReceiverId == user.Id).Include(m => m.Sender).OrderByDescending(m => m.UploadDate).ToListAsync();
            foreach (Message message in messages.Where(m=>m.IsRead == false))
            {
                message.IsRead = true;
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
            }

            int messagesCount;
            IEnumerable<Message> messagesPerPages;
            int pageSize = ItemCountPerPage != null ? (int)ItemCountPerPage : 5;
            
            messagesCount = messages.Count();
            messagesPerPages = messages;
            
            if (!String.IsNullOrEmpty(Name))
            {
                messagesPerPages = messagesPerPages.Where(s => s.Name.IndexOf(Name) != -1);
                messagesCount = messagesPerPages.Count();
            }

            messagesPerPages =
                messagesPerPages.OrderByDescending(m => m.UploadDate).ThenBy(g => g.Name)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList();
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = messagesCount };
            IndexViewModel<Message> ivm = new IndexViewModel<Message>
            {
                PageInfo = pageInfo,
                Objects = messagesPerPages,
                Name = Name ?? ""
            };
            return View(ivm);
        }
        [HttpGet]
        public async Task<ActionResult> Create(string Id)
        {
            if(Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            /*ApplicationUser user = UserManager.FindById(receiverId);
            if (user == null)  return HttpNotFound();*/
            ViewBag.ReceiverId = Id;
            var Sender = await UserManager.FindByEmailAsync(User.Identity.Name);
            ViewBag.SenderId = Sender.Id;
            ViewBag.SenderName = Sender.Name;
            return PartialView();
        }
        public ActionResult UnreadMesagesCountSelect()
        {
            ApplicationUser user = db.Users.Where(u => String.Equals(u.Email, User.Identity.Name)).FirstOrDefault();

            ViewBag.UnreadMesagesCount = user != null ? db.Messages.Where(m => m.ReceiverId == user.Id && m.IsRead == false).Count() : 0;

            return PartialView();
        }
        /*public ActionResult Create1()
        {
            
            return View();
        }*/
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await db.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return PartialView(message);
        }
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await db.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            
            db.Messages.Remove(message);
            await db.SaveChangesAsync();
            return RedirectToAction("MessagesList");
            
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyDistanceLearningSystem/Views/Groups/BindTeachers.cshtml
@model List<MyDistanceLearningSystem.Models.Discipline>
@using MyDistanceLearningSystem.Models
<!--<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Привязка преподавателей</h4>-->
    <!--</div>-->
   <!-- <div class="modal-body">-->
        @{
            /*for (int i = 0; i < Model.Count; i++)
            {

                @Html.HiddenFor(d => d[i].Id)

                @Html.DisplayFor(m => m[i].Name)
                <div>
                    @for (int j = 0; j < Model[i].Teachers.Count; j++)
                    {
                    @Html.HiddenFor(m => m[i].Teachers.ToArray()[j].Id)

                    @Html.DisplayFor(m => m[i].Name)
                    <input type="radio" id="Teachers" name="Teachers" value="@(Model[i].Teachers.ToArray()[j].Id+"_"+Model[i].Id)"
                           @(Model[i].Teachers.ToArray()[j].GroupId == ViewBag.GroupId ? "checked=\"checked\"" : "") />@Model[i].Teachers.ToArray()[j].Name <br />
                        }
                    </div>
            }*/
            int i = 0;
            foreach (Discipline d in Model)
            {
                <div>
                    @Html.Display(d.Name)
                    <p>@d.Name</p>

                    @foreach (var u in d.Teachers.ToList())
                    {

                        <input type="radio" class="teachers-helper" name="teachers-helper[@i]" value="@(u.Id)"
                               @(u.GroupId == ViewBag.GroupId ? "checked=\"checked\"" : "") />@u.Name <br />

                    }

                    @Html.Hidden("teachers")
                </div>
                <br />
                i++;
            }
            <!--<div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>-->

        }
    <!--</div>-->
<!--</div>-->

MyDistanceLearningSystem/Views/Groups/ChatWithWebSockets.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Простой чат</title>
</head>
<body>
    <input type="text" id="user" />
    <input type="text" id="message" />
    <input type="button" value="send" id="send" />
    <div id='messages'></div>

    <script type="text/javascript">
        var socket,
            $txt = document.getElementById('message'),
            $user = document.getElementById('user'),
            $messages = document.getElementById('messages');

        if (typeof (WebSocket) !== 'undefined') {
            socket = new WebSocket("ws://localhost/MyDistanceLearningSystem/ChatHandler.ashx");
        } else {
            socket = new MozWebSocket("ws://localhost/MyDistanceLearningSystem/ChatHandler.ashx");
        }

        socket.onmessage = function (msg) {
            var $el = document.createElement('p');
            $el.innerHTML = msg.data;
            $messages.appendChild($el);
        };

        socket.onclose = function (event) {
            alert('Мы потеряли её. Пожалуйста, обновите страницу');
        };

        document.getElementById('send').onclick = function () {
            socket.send($user.value + ' : ' + $txt.value);
            $txt.value = '';
        };
    </script>
</body>
</html>

MyDistanceLearningSystem/Views/Groups/Create.cshtml
@model MyDistanceLearningSystem.Models.Group
@using MyDistanceLearningSystem.Models
@{
    ViewBag.Title = "Create group";
}

<h2>Создание группы</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrainingProgramId, "TrainingProgramId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TrainingProgramId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainingProgramId, "", new { @class = "text-danger" })
            </div>
            <br />
            <br />
            <!--<div class="col-md-10 col-md-push-2">/*Html.ActionLink("Привязать преподавателей", "BindTeachers", new { groupId = Model.Id, trainingProgramId = Model.TrainingProgramId /*$("#TrainingProgramId :selected").val()*/ }, new { id = "bind_teachers", class = "btn btn-success btn-xs", title = "Привязать преподавателей" })*/</div>-->
            <div class="form-group">
                @Html.Label("Преподаватели", new { @class = "control-label col-md-2" })
                <div class="col-md-10" id="container" style="/*display:none*/">
                    <div style="height: 200px; width:280px; overflow-y: scroll;" id="teachers_list">
                        @{ int i = 0;
                            foreach (Discipline d in ViewBag.Disciplines)
                            {
                                <div>
                                    @Html.Display(d.Name)
                                    <p>@d.Name</p>

                                    @foreach (var u in d.Teachers.ToList())
                                    {

                                        <input type="radio" class="teachers-helper" name="teachers[@i]" value="@(u.Id)" />@u.Name <br />

                                    }
                                    @Html.Hidden("teachers")
                                </div>
                                <br />
                                i++;
                                <br />
                            }
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Students, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div style="height: 200px; width:280px; overflow-y: scroll;" id="students">
                    @{
                        List<ApplicationUser> students = ViewBag.Students;
                        foreach (ApplicationUser s in students)
                        {
                            <input type="checkbox" name="selectedStudents" value="@s.Id" />@s.Name <br />
                        }
                    }
                </div>
            </div>
        </div>
        @Html.Hidden("referrer", ViewBag.Referrer as String)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@ViewBag.Referrer">Back to List</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        function teachers_helper_function() {
            $("#container input:checked").each(function (index, element) {
                $(this).parent().find("input[type='hidden']").val($(this).val());
                console.log($(this).val());
            });
            $(".teachers-helper").change(function () {
                console.log($(this).val());
                $(this).parent().find("input[type='hidden']").val($(this).val());
            });
        }
        teachers_helper_function();
            $(function () {
                $.ajaxSetup({ cache: false });
                $("#TrainingProgramId").change(function (e) {
                    e.preventDefault();
                    $.get("@Url.RouteUrl(new { controller = "Groups", action = "BindTeachers" })", { isGroupCreate : true, trainingProgramId : $("#TrainingProgramId :selected").val() }, function (data) {
                        $('#teachers_list').html(data);
                        teachers_helper_function();
                    });
                });
            })
    </script>
}

MyDistanceLearningSystem/Views/Groups/Delete.cshtml
@model MyDistanceLearningSystem.Models.Group

@{
    ViewBag.Title = "Delete group";
}

<h2>Удаление группы</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TrainingProgram.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingProgram.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        @if (ViewBag.Students.Count > 0)
        {
            <dt>
                Связи
            </dt>

            <dd>
                <div>
                    Студенты:
                    <ul>
                        @{
                            var students = ViewBag.Students;
                            foreach (var s in students)
                            {
                                <li>@s.Name</li>
                            }
                        }
                    </ul>
                </div>
            </dd>
       }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.Hidden("referrer", ViewBag.Referrer as String)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a href="@ViewBag.Referrer">Back to List</a>
        </div>
    }
</div>

MyDistanceLearningSystem/Views/Groups/Details.cshtml
@model MyDistanceLearningSystem.Models.Group
<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Информация о группе</h4>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.TrainingProgram.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TrainingProgram.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

    </div>
</div>

MyDistanceLearningSystem/Views/Groups/StudentsInfo.cshtml
@model MyDistanceLearningSystem.Models.ApplicationUser
<script type="text/javascript">
    var $text = $('.user-info-text'),
    $button = $('.user-info-btn');
    $button.click(function () {
        if ($text.is(':visible')) {
            $text.slideUp();
            $button.find(".glyphicon").removeClass("glyphicon-chevron-up").addClass("glyphicon-chevron-down")
        } else {
            $button.find(".glyphicon").removeClass("glyphicon-chevron-down").addClass("glyphicon-chevron-up")
            $text.slideDown();
        }
    });
</script>
<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Информация о пользователе</h4>
    </div>
    <div class="modal-body">
        <!--сведения о самом пользователе-->
        <button class="btn user-info-btn center-block" style="width: 100%;">
            <span>Информация о студенте</span> <span class="glyphicon glyphicon-chevron-down"></span>
        </button>
        <dl class="dl-horizontal user-info-text" style="display: none;">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Surname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Surname)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

        </dl>


        <!--сведения об успеваемости-->
        <div class="home-works-container">
            @if (Model.ApplicationFiles.Count != 0)
            {
                <h4 title="Дисциплина @ViewBag.Teacher.Discipline.Name">@ViewBag.Teacher.Discipline.Name</h4>
                foreach (var file in Model.ApplicationFiles.Where(f=>f.DisciplineId == ViewBag.Teacher.Discipline.Id))
                {
                    <span title="Скачать @file.DisplayName">
                        @Html.ActionLink(file.DisplayName, "GetFile", "ApplicationFiles", new { id = file.Id, isHomeWork = true }, null)
                    </span>
                }

            }
        </div>
        <hr />
    </div>
</div>

MyDistanceLearningSystem/Views/Groups/StudentsList.cshtml
@model IEnumerable<MyDistanceLearningSystem.Models.ApplicationUser>
@{
    ViewBag.Title = "StudentsList";
}

<h2>Студенты</h2>


<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div class="spinner text-center">
    <i class="load"></i>
</div>
<table class="table">
    <tr>
        <th>
            Имя
        </th>
        <th>
            Фамилия
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <span class="user" id="@item.Id">
                    @Html.DisplayFor(modelItem => item.Name)
                </span>
            </td>
            <td>
                <span class="user" id="@item.Id">
                    @Html.DisplayFor(modelItem => item.Surname)
                </span>
            </td>
            <td>
                <!--Html.ActionLink("Edit", "AdminEdit", new { id = item.Id }) |
                Html.ActionLink("Delete", "AdminDelete", new { id = item.Id, url = Request.RawUrl })-->
                @Html.ActionLink("Написать сообщение", "Create", "Messages", new { Id = item.Id }, new { Id = item.Id, @class = "message-create" })
            </td>
        </tr>
    }

</table>
<br />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/js_functions")

    <script type="text/javascript">

        modal_window("user", "@Url.RouteUrl(new { controller = "Groups", action = "StudentsInfo" })");
        modal_window("message-create", "@Url.RouteUrl(new { controller = "Messages", action = "Create" })");

    </script>
}